### ISSUE TITLE
Gitignore latest commit

### ISSUE THREAD

**Issue by brigid-book** [STL-WomenPlus-Mar22-LiftOff/bucket-list-adventures#6]
https://github.com/STL-WomenPlus-Mar22-LiftOff/bucket-list-adventures/commits/main/.gitignore
The most recent gitignore commit (6fff426) removed almost everything in it, which means it ignores barely any of the files that it should. With the most recent commit of gitignore, it says I have 354 changes, almost all of which are auto-generated files that are supposed to be ignored. With Soniya's original version, it works fine and I have only 11 changes. This file should be changed back to this original version.

**Comment by btormino** [comment]
If you remember from last night, we only needed what we put in there. What we put covered the folders that held the problem files.  We don't need to go back to the original, but perhaps there's a folder name that we need to add.

**Comment by soniya1987** [comment]
I have restored the gitignore file to the previous version. please check and let me know if you have any issues.
